# file: roles/queuetier/handlers/main.yml
- name: Reload supervisord config
  shell: supervisorctl update
  changed_when: False

- name: Reload supervisord config (Debian)
  shell: supervisorctl update
  changed_when: False