# file: roles/common/tasks/composer.yml
- name: Check if composer is installed
  tags: composer
  stat:
    path: /usr/bin/composer
  register: composer_binary

- name: Download Composer installer
  tags: composer
  when: composer_binary.stat.exists == false
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Install composer
  tags: composer
  command: php /tmp/composer-setup.php --install-dir=/usr/bin --filename=composer
  when: composer_binary.stat.exists == false

- name: Update to latest composer version
  tags: composer
  command: composer selfupdate
  when: composer_binary.stat.exists == true
  changed_when: false