# file: roles/webtier/tasks/main.yml
- include: ondrej.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'  
- include: php.yml
- include: php-fpm.yml
- include: composer.yml
- include: nginx.yml
- include: cron.yml
- include: letsencrypt.yml
  when: enable_ssl|default(false)|bool == true
- include: redis.yml
