# file: roles/webtier/tasks/nginx.yml
- name: Make sure apache related packages are removed
  tags: nginx
  apt: name="{{ packages }}" state=absent purge=yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  vars:
      packages:
      - apache2
      - apache2-utils
  
- name: Install nginx
  tags: nginx
  apt: name=nginx state=present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure nginx user exists
  tags: nginx
  user:
    name: nginx
    comment: nginx user
    createhome: false
    generate_ssh_key: false
    shell: /bin/false
    system: yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  
- name: Kill PID which use 80 port.
  ignore_errors: yes
  tags: letsencrypt
  raw: sudo fuser -k 80/tcp

- name: Make sure nginx is running and is started on boot
  tags: nginx
  service: name=nginx state=started enabled=yes

- name: Make sure nginx is configured
  tags: nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - Restart nginx

- name: Install apache2-utils for auth testing and staging.
  tags: nginx
  apt: name=apache2-utils state=present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure apache2-utils is configured
  tags: nginx
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: '{{ htpasswd_credentials.login }}'
    password: '{{ htpasswd_credentials.password }}'
  with_dict: "{{ htpasswd_credentials }}"

- name: Make sure nginx virtual hosts are configured for testing
  tags: nginx
  template: src=nginx-virtualhost-testing.conf.j2 dest=/etc/nginx/conf.d/testing.{{ item.value.servernames[0] }}.conf
  with_dict: "{{ virtualhosts }}"
  when: enable_ssl|default(false)|bool == false
  notify:
    - Restart nginx

- name: Make sure nginx virtual hosts are configured for staging
  tags: nginx
  template: src=nginx-virtualhost-staging.conf.j2 dest=/etc/nginx/conf.d/staging.{{ item.value.servernames[0] }}.conf
  with_dict: "{{ virtualhosts }}"
  when: enable_ssl|default(false)|bool == false
  notify:
    - Restart nginx

- name: Make sure nginx virtual hosts are configured for production
  tags: nginx
  template: src=nginx-virtualhost-production.conf.j2 dest=/etc/nginx/conf.d/{{ item.value.servernames[0] }}.conf
  with_dict: "{{ virtualhosts }}"
  when: enable_ssl|default(false)|bool == false
  notify:
    - Restart nginx

- name: Create public directory for testing
  tags: nginx
  file: path=/var/www/testing.{{ item.value.servernames[0] }}/public state=directory owner=www-data group=www-data mode=0775
  with_dict: "{{ virtualhosts }}"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Create public directory for staging
  tags: nginx
  file: path=/var/www/staging.{{ item.value.servernames[0] }}/public state=directory owner=www-data group=www-data mode=0775
  with_dict: "{{ virtualhosts }}"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Create public directory for production
  tags: nginx
  file: path=/var/www/{{ item.value.servernames[0] }}/public state=directory owner=www-data group=www-data mode=0775
  with_dict: "{{ virtualhosts }}"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

