# file: roles/common/tasks/ntp.yml
- name: Install ntp
  apt: name=ntp state=present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure ntpd is running
  service: name=ntp state=started
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure ntpd is started on boot
  service: name=ntp enabled=yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
